### ISSUE TITLE
No displays detected try dropping screen option

### ISSUE THREAD

**Issue by etec-masterofsynapse** [plainlab/plainprinter#12]
## Prerequisites

- [?] Using yarn
- [?] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [?] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [?] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [?] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Current Behavior

App displayed the error above after running through 233 pages.

## Steps to Reproduce

Error: No displays detected try dropping screen option
at /Applications/PlainPrinter.app/Contents/Resources/app.asar/node_modules/screenshot-desktop/lib/darwin/index.js:15:21
at new Promise (<anonymous>)
at performScreenCapture (/Applications/PlainPrinter.app/Contents/Resources/app.asar/node_modules/screenshot-desktop/lib/darwin/index.js:11:44)
at /Applications/PlainPrinter.app/Contents/Resources/app.asar/node_modules/screenshot-desktop/lib/darwin/index.js:64:53
at process.buff (node:internal/process/task_queues:96:5)
at /Applications/PlainPrinter.app/Contents/Resources/app.asar/dist/main/webpack:/src/main/main.ts:284:15
at node:electron/js2c/browser_init:189:563

## Your Environment

- Node version: ?
- PlainPrinter version or branch: 0.2.0
- Operating System and version: macOS 12.5.1
- Link to your project: ?

**Comment by manhtai** [comment]
Hi, do you use multiple screen? This might related to this open issue: https://github.com/bencevans/screenshot-desktop/issues/171

A possible fix may be to use only one screen, not tested yet.

**Comment by etec-masterofsynapse** [comment]
I only have one display connected via HDMI to my Mac Mini.

**Comment by manhtai** [comment]
That’s “external” actually, this guy has a mac mini too https://github.com/bencevans/screenshot-desktop/issues/171#issuecomment-781284912. I can’t help with this case for now though.

**Comment by etec-masterofsynapse** [comment]
Well, the Mac mini can't have an internal display since it's a closed box.
However it seems that this error also occurs when you use your app with any kind of remote control software, like VNC or AnyDesk. I tried it without and got to the needed 630 pages, and no error.
