### ISSUE TITLE
Unknown Image Format

### ISSUE THREAD

**Issue by kusold** [plainlab/plainprinter#16]
## Prerequisites

OS: MacOS 12.6
PlainPrinter Version: 0.2.2

## Current Behavior

When I click "Start Printing", I receive a popup that contains the following:

```
Error: Unknown image format.
at Function.open (/Applications/PlainPrinter.app/Contents/Resources/app.asar/node_modules/pdfkit/lib/image.js:34:13)
at PDFDocument.openImage (/Applications/PlainPrinter.app/Contents/Resources/app.asar/node_modules/pdfkit/lib/mixins/images.js:122:24)
at PDFDocument.image (/Applications/PlainPrinter.app/Contents/Resources/app.asar/node_modules/pdfkit/lib/mixins/images.js:27:22)
at /Applications/PlainPrinter.app/Contents/Resources/app.asar/dist/main/webpack:/src/main/main.ts:290:13
at node:electron/js2c/browser_init:189:563
```
## Steps to Reproduce

1. Open Plain Printer on a Mac

2. Configure,and press Start 

3. Error occurs
![image](https://user-images.githubusercontent.com/509966/193914568-3e8ff69e-77b8-4be9-b260-3e3ccc93cb2f.png)

## Possible Solution (Not obligatory)

I have found references that pdfkit [requires uppercase extensions](https://github.com/foliojs/pdfkit/issues/1386). Grabbing the images as `*.PNG` may work.

## Context

This causes the printing feature to not work.

## Your Environment

- Node version: v18.10.0
- PlainPrinter version or branch: 0.2.2 Release
- Operating System and version: MacOS 12.6

**Comment by manhtai** [comment]
Hello, thanks for the report. I'm just testing on my macOS 12.6 with M1 chip, it works fine, so no clues how to fix this.

**Comment by kusold** [comment]
I’m using an Intel Mac, so that might be the difference. I also verified my file system is case-insensitive (the standard).

**Comment by manhtai** [comment]
It works fine on my Intel Mac also (Mac 16in 2019). Same macOS version.

**Comment by Hao-Xue-Git** [comment]
I have an Intel Mac 2019 15 inch, and have the same problem.

**Comment by bemfica** [comment]
+1 here. @kusold do you use multiple monitors? No idea if this may be related, but still.

**Comment by kusold** [comment]
I might have been using multiple monitors. My use case for this tool has passed, as well as my Intel Mac, so I haven’t attempted again since running into this bug.
